# On every push this script is executed
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Rebuild at 12 Midnight every day
  schedule:
    - cron: '0 0 * * *'

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install zola
        run: sudo snap install --edge zola
      - name: Build site
        run: zola build
      - name: Upload site to GitHub Pages
        id: deployment
        uses: actions/actions/upload-pages-artifact@v3
        with:
          path: public/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
