# On every push this script is executed
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Rebuild at 12 Midnight every day
  schedule:
    - cron: '0 0 * * *'

env:
  CNANE: "test.touhoufest.org"

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: echo $CNAME > static/CNAME
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
